# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: pip
    command: pip install --upgrade pip
  - name: numpy
    command: pip install numpy --upgrade numpy
  - name: pandas
    command: pip install pandas --upgrade pandas
  - name: matplotlib
    command: pip install matplotlib --upgrade matplotlib

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

image:
  file: .gitpod.Dockerfile
